### PR TITLE
Nano ID 2.0

### PR DESCRIPTION
**Pull request by telesvar**

### CODE REVIEW

**Comment by puyuan** [comment]
Thanks for the changes. I have a few things going on today, I will try to merge and test it again over weekend.

**Comment by telesvar** [comment]
You are welcome

**Comment by puyuan** [comment]
Overall looks good,  but just one question here.  Porting non-secure.generate like in the JS case to python is a little bit confusing and a lot more complex. 



# 1

This is  simple 

```
from nanoid import generate, non_secure_generate
```



# 2 

and this is a lot more complex


```
from nanoid import generate
from nanoid.non_secure import generate (so which generate, the name is same)

# or using it as module
from nanoid import non_secure
non_secure.generate()

# but why not also have this, to make it consistent
from nanoid import secure
secure.generate()

# For 2,  this paradigm takes more brain power to follow
```

I can show you a version in v2.0 merge.  And you can review it, maybe better?

**Comment by telesvar** [comment]
I would like to see your version too.

As for 2, using `as` is the only solution, actually.
```python
from nanoid import generate
from nanoid.non_secure import generate as non_secure # <=

generate()
non_secure()
```

Not the easiest to follow, but somehow concise. Someone, who is an expert in creating libraries may argue with me.

Again, please, share with me your vision on how this library should be structured.

**Comment by puyuan** [comment]
My aim is for simplicity.  Using `as` is of course allowed, but having to rename function names by default makes it a little bit complex. i.e. when you are using both functions.  This is quite a simple library as of now, adding hierarchies and renaming make it complex. 

Please see my PR in v2.0.  I actually took your entire change in v2.0 PR, and deleted my nanoid.py implementation.  I hope I am not too picky except on the interface.

**Pull request merged**
